# Generated by Django 5.0.4 on 2024-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addRestaurentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commpanyName', models.CharField(max_length=50)),
                ('issuedBy', models.CharField(max_length=50)),
                ('expiryDate', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
