# Generated by Django 5.0.4 on 2024-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactFullName', models.CharField(max_length=50)),
                ('contactEmail', models.CharField(max_length=50)),
                ('contactPhoneNumber', models.IntegerField()),
                ('contactSubject', models.CharField(max_length=50)),
                ('contactMessage', models.TextField()),
            ],
        ),
    ]
