# Generated by Django 5.0.4 on 2024-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('cause', models.CharField(max_length=50)),
                ('damage', models.CharField(max_length=50)),
                ('comments', models.TextField()),
            ],
        ),
    ]
