# Generated by Django 4.0.5 on 2024-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='addRestaurentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commpanyName', models.CharField(max_length=50)),
                ('issuedBy', models.CharField(max_length=50)),
                ('expiryDate', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
