# Generated by Django 4.0.5 on 2024-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
            ],
        ),
    ]
