# Generated by Django 4.0.5 on 2024-05-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_face'),
    ]

    operations = [
        migrations.DeleteModel(
            name='face',
        ),
    ]
