# Generated by Django 4.0.5 on 2024-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
