# Generated by Django 5.0.4 on 2024-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='assigned',
            field=models.IntegerField(null=True),
        ),
    ]
