# Generated by Django 5.0.4 on 2024-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_team_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assigned', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='assigned',
        ),
    ]
