# Generated by Django 5.0.4 on 2024-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_assignedteam_remove_team_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedteam',
            name='assigned',
            field=models.IntegerField(default=0),
        ),
    ]
