# Generated by Django 5.0.4 on 2024-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_assignedteam_cause_assignedteam_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedteam',
            name='complete',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
